import { jsPDF } from "jspdf";

export type InvoicePdfInput = {
  invoiceNumber: string;
  bookingId: number;
  listingTitle?: string | null;
  subtotal: number;
  commissionFee: number;
  vatRateBasisPoints: number;
  vatAmount: number;
  total: number;
  currency: string;
  status: string;
  paymentMethod?: string | null;
  paymentStatus?: string | null;
  startDate?: string | Date | null;
  endDate?: string | Date | null;
  issuedAt?: string | Date | null;
};

const money = (value: number, currency: string) => `${new Intl.NumberFormat("fr-MA").format(value)} ${currency}`;
const date = (value?: string | Date | null) => value ? new Date(value).toLocaleDateString("fr-MA") : "—";

export function generateInvoicePdf(input: InvoicePdfInput): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const width = 210;
  const margin = 18;
  const vatRate = (input.vatRateBasisPoints / 100).toFixed(2).replace(/\.00$/, "");

  doc.setFillColor(11, 60, 93);
  doc.rect(0, 0, width, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.text("B2-RENT", margin, 14);
  doc.setFontSize(10);
  doc.text("FACTURE / INVOICE", margin, 22);

  doc.setTextColor(18, 24, 38);
  doc.setFontSize(11);
  doc.text(`Invoice no. ${input.invoiceNumber}`, margin, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.text(`Booking #${input.bookingId}`, margin, 51);
  doc.text(`Issued: ${date(input.issuedAt)}`, margin, 57);
  doc.text(`Status: ${input.status}`, width - margin, 44, { align: "right" });
  doc.text(`Payment: ${input.paymentStatus || "—"}`, width - margin, 51, { align: "right" });
  doc.text(`Method: ${input.paymentMethod || "—"}`, width - margin, 57, { align: "right" });

  doc.setFillColor(245, 247, 250);
  doc.roundedRect(margin, 68, width - margin * 2, 28, 3, 3, "F");
  doc.setTextColor(11, 60, 93);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("RENTAL DETAILS", margin + 7, 78);
  doc.setTextColor(18, 24, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.text(`Listing: ${input.listingTitle || "Rental listing"}`, margin + 7, 86);
  doc.text(`Period: ${date(input.startDate)} - ${date(input.endDate)}`, margin + 7, 92);

  let y = 116;
  const labelX = margin + 7;
  const amountX = width - margin - 7;
  const row = (label: string, amount: number, accent = false) => {
    doc.setTextColor(accent ? 11 : 70, accent ? 60 : 75, accent ? 93 : 85);
    doc.setFont("helvetica", accent ? "bold" : "normal");
    doc.text(label, labelX, y);
    doc.text(money(amount, input.currency), amountX, y, { align: "right" });
    y += 10;
  };

  doc.setDrawColor(220, 225, 232);
  doc.line(margin, y - 7, width - margin, y - 7);
  row("Subtotal / base rent", input.subtotal);
  row("Platform commission (included in settlement)", input.commissionFee);
  row(`TVA (${vatRate}%)`, input.vatAmount);
  doc.line(margin, y - 5, width - margin, y - 5);
  y += 5;
  row("TOTAL À PAYER / TOTAL", input.total, true);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 105, 115);
  const notes = [
    "Payment gateway status is simulated for this prototype.",
    "VAT rate and amounts are persisted with the invoice for auditability.",
    "This document is an electronic invoice generated by B2-Rent.",
  ];
  notes.forEach((note, index) => doc.text(note, margin, 255 + index * 6));
  doc.text("B2-Rent Morocco · support available from your account", margin, 281);
  return doc.output("blob");
}
