CREATE TABLE `commercial_lease_contracts` (
	`contract_id` int AUTO_INCREMENT NOT NULL,
	`booking_id` int NOT NULL,
	`landlord_id` int NOT NULL,
	`tenant_id` int NOT NULL,
	`reference` varchar(80) NOT NULL,
	`lease_type` enum('commercial','professional') NOT NULL,
	`landlord_name` varchar(255) NOT NULL,
	`tenant_name` varchar(255) NOT NULL,
	`premises` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`start_date` timestamp NOT NULL,
	`end_date` timestamp NOT NULL,
	`monthly_rent` int NOT NULL,
	`deposit` int NOT NULL DEFAULT 0,
	`pdf_key` varchar(512),
	`status` enum('Draft','Generated','Signed') NOT NULL DEFAULT 'Generated',
	`legal_notice` text NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `commercial_lease_contracts_contract_id` PRIMARY KEY(`contract_id`),
	CONSTRAINT `commercial_lease_contracts_booking_id_unique` UNIQUE(`booking_id`),
	CONSTRAINT `commercial_lease_contracts_reference_unique` UNIQUE(`reference`)
);
