import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Building2, CalendarCheck, Check, Plus, TrendingUp, X, Trash2, WalletCards, Pencil, MessageCircle, RefreshCw, Copy, Eye, Phone, Power, BarChart3, Download } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { AdvancedMediaUpload } from "@/components/AdvancedMediaUpload";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

const labels = {
  office: "مكتب مستقل",
  coworking: "مساحة عمل مشتركة",
  meeting: "قاعة اجتماعات",
  headquarters: "مقر شركة",
} as const;

export default function HostDashboard() {
  const { user, loading } = useAuth();
  const listings = trpc.agency.listings.useQuery(undefined, { enabled: !!user });
  const overview = trpc.agency.overview.useQuery(undefined, { enabled: !!user });
  const analyticsCsv = trpc.agency.exportAnalyticsCsv.useQuery(undefined, { enabled: false });
  const bookings = trpc.bookings.ownerList.useQuery(undefined, { enabled: !!user });
  const createListing = trpc.listings.create.useMutation({ onSuccess: async () => { await Promise.all([listings.refetch(), overview.refetch()]); toast.success("تم نشر العرض مباشرة بعد اجتياز الفحص."); setShowForm(false); } });
  const updateStatus = trpc.bookings.ownerUpdateStatus.useMutation({ onSuccess: () => { bookings.refetch(); toast.success("تم تحديث حالة الحجز"); } });
  const removeListing = trpc.listings.remove.useMutation({ onSuccess: async () => { await Promise.all([listings.refetch(), overview.refetch()]); toast.success("تم حذف الإعلان"); }, onError: (error) => toast.error(error.message) });
  const updateListing = trpc.listings.update.useMutation({ onSuccess: async () => { await Promise.all([listings.refetch(), overview.refetch()]); setEditingId(null); toast.success("تم تحديث العرض ونشر التعديلات."); }, onError: (error) => toast.error(error.message) });
  const toggleAvailability = trpc.listings.toggleAvailability.useMutation({ onSuccess: async () => { await Promise.all([listings.refetch(), overview.refetch()]); toast.success("تم تحديث حالة التوفر."); }, onError: (error) => toast.error(error.message) });
  const setAvailability = trpc.listings.setAvailability.useMutation({ onSuccess: () => { listings.refetch(); toast.success("تم تحديث تقويم التوفر"); }, onError: (error) => toast.error(error.message) });
  const saveIcal = trpc.listings.saveIcalSettings.useMutation({ onSuccess: async () => { await listings.refetch(); toast.success("تم حفظ إعدادات iCal"); }, onError: (error) => toast.error(error.message) });
  const syncIcal = trpc.listings.syncIcalNow.useMutation({ onSuccess: async (result) => { await listings.refetch(); toast.success(result.synced ? `تم استيراد ${result.count ?? 0} فترة من التقويم` : "لا يوجد رابط iCal مضبوط"); }, onError: (error) => toast.error(error.message) });
  const financials = trpc.admin.ownerFinancials.useQuery(undefined, { enabled: !!user && (user.role === "owner" || user.role === "admin") });
  const requestPayout = trpc.payouts.request.useMutation({ onSuccess: async () => { toast.success("تم إرسال طلب السحب للمراجعة"); await financials.refetch(); setPayoutAmount(""); }, onError: (error) => toast.error(error.message) });
  const [form, setForm] = useState({ title: "", city: "الدار البيضاء", officeType: "office", rentalPeriod: "monthly", price: "", description: "", amenities: [] as string[], imageUrl: "" });
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [availabilityDraft, setAvailabilityDraft] = useState({ listingId: 0, start: "", end: "" });
  const [payoutAmount, setPayoutAmount] = useState("");
  const [icalDrafts, setIcalDrafts] = useState<Record<number, string>>({});
  const [payoutMethod, setPayoutMethod] = useState<"bank_transfer" | "cash_plus" | "wafacash">("bank_transfer");
  const fallbackActiveBookings = useMemo(() => (bookings.data ?? []).filter((b) => b.status === "Pending" || b.status === "Confirmed").length, [bookings.data]);
  const fallbackMonthlyRevenue = useMemo(() => (bookings.data ?? []).filter((b) => b.status === "Confirmed").reduce((sum, b) => sum + Number(b.netProfit ?? b.totalPrice ?? 0), 0), [bookings.data]);
  const activeBookings = overview.data?.activeBookings ?? fallbackActiveBookings;
  const monthlyRevenue = overview.data?.netRevenue ?? fallbackMonthlyRevenue;
  const downloadAnalyticsCsv = async () => {
    try {
      const result = await analyticsCsv.refetch();
      if (!result.data) return toast.error("تعذر إنشاء ملف الإحصائيات");
      const blob = new Blob([result.data.csv], { type: "text/csv;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = result.data.filename;
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      URL.revokeObjectURL(url);
      toast.success("تم تنزيل ملف إحصائيات الوكالة");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "تعذر تنزيل الملف");
    }
  };

  if (loading) return <div className="container py-24 text-center">جاري تحميل لوحة المالك...</div>;
  if (!user) return <div className="container py-24 text-center">يرجى تسجيل الدخول للوصول إلى لوحة المالك.</div>;
  if (user.role !== "owner" && user.role !== "admin") return <div className="container py-24 text-center"><h1 className="text-2xl font-bold">هذه اللوحة مخصصة للملاك</h1><Link href="/my-bookings"><Button className="mt-6">الانتقال إلى حجوزاتي</Button></Link></div>;

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.title || !form.price) return toast.error("أدخل اسم المكتب والسعر");
    if (editingId) {
      updateListing.mutate({ id: editingId, title: form.title, city: form.city, pricePerDay: Number(form.price), description: form.description, officeType: form.officeType, rentalPeriod: form.rentalPeriod as "daily" | "monthly" | "yearly", amenities: form.amenities, imageUrl: form.imageUrl || undefined });
      return;
    }
    createListing.mutate({ title: form.title, city: form.city, category: "office", pricePerDay: Number(form.price), description: form.description, officeType: form.officeType, rentalPeriod: form.rentalPeriod as "daily" | "monthly" | "yearly", amenities: form.amenities, imageUrl: form.imageUrl || undefined });
  };
  const toggleAmenity = (value: string) => setForm((current) => ({ ...current, amenities: current.amenities.includes(value) ? current.amenities.filter((item) => item !== value) : [...current.amenities, value] }));

  return <div className="container py-8 space-y-8" dir="rtl">
    <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-muted-foreground">مساحة المالك</p><h1 className="text-3xl font-black">لوحة إدارة المكاتب</h1></div><div className="flex flex-wrap gap-2"><Link href="/host/settings"><Button type="button" variant="outline"><Building2 className="ml-2 h-4 w-4" />إعدادات الوكالة</Button></Link><Button type="button" variant="outline" onClick={downloadAnalyticsCsv} disabled={analyticsCsv.isFetching}><Download className="ml-2 h-4 w-4" />{analyticsCsv.isFetching ? "جاري التصدير..." : "تصدير CSV"}</Button><Button onClick={() => setShowForm((value) => !value)} className="bg-[var(--brand-amber)] text-white"><Plus className="ml-2 h-4 w-4" />إضافة مكتب جديد</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={<TrendingUp />} title="الصافي المؤكد" value={`${Number(monthlyRevenue).toLocaleString("fr-MA")} MAD`} /><Stat icon={<CalendarCheck />} title="الحجوزات النشطة" value={String(activeBookings)} /><Stat icon={<Building2 />} title="إجمالي العروض" value={String(overview.data?.totalListings ?? listings.data?.length ?? 0)} /><Stat icon={<Eye />} title="المشاهدات" value={String(overview.data?.views ?? 0)} /><Stat icon={<MessageCircle />} title="نقرات التواصل" value={String((overview.data?.whatsappClicks ?? 0) + (overview.data?.contactClicks ?? 0))} /></div>
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2 text-sm font-bold"><MessageCircle className="h-4 w-4 text-emerald-600" />نقرات واتساب</div><p className="mt-3 text-3xl font-black">{overview.data?.whatsappClicks ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">إجمالي النقرات على مراسلة الوكالة</p></div><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2 text-sm font-bold"><Phone className="h-4 w-4 text-blue-600" />نقرات الاتصال</div><p className="mt-3 text-3xl font-black">{overview.data?.contactClicks ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">إجمالي طلبات الاتصال المسجلة</p></div><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2 text-sm font-bold"><Power className="h-4 w-4 text-amber-600" />حالة التوفر</div><p className="mt-3 text-3xl font-black">{overview.data?.availableListings ?? 0}<span className="text-base font-medium text-muted-foreground"> متاح</span></p><p className="mt-1 text-xs text-muted-foreground">{overview.data?.unavailableListings ?? 0} عرض غير متاح حالياً</p></div></section>
    <section className="rounded-3xl border bg-card p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><WalletCards className="h-5 w-5 text-[var(--brand-amber)]" /><h2 className="text-xl font-bold">الأرباح والتسويات</h2></div><div className="grid gap-4 sm:grid-cols-4"><Stat title="الإجمالي" value={`${Number(financials.data?.gross ?? 0).toLocaleString("fr-MA")} MAD`} /><Stat title="عمولة المنصة" value={`${Number(financials.data?.platformFees ?? 0).toLocaleString("fr-MA")} MAD`} /><Stat title="الصافي" value={`${Number(financials.data?.net ?? 0).toLocaleString("fr-MA")} MAD`} /><Stat title="المصروف" value={`${Number(financials.data?.paid ?? 0).toLocaleString("fr-MA")} MAD`} /></div><form className="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto]" onSubmit={(event) => { event.preventDefault(); const amount = Number(payoutAmount); if (!amount || amount <= 0) return toast.error("أدخل مبلغاً صحيحاً"); requestPayout.mutate({ amount, method: payoutMethod }); }}><input type="number" min="1" className="rounded-xl border bg-background p-3" placeholder="مبلغ السحب بالدرهم" value={payoutAmount} onChange={(event) => setPayoutAmount(event.target.value)} /><select className="rounded-xl border bg-background p-3" value={payoutMethod} onChange={(event) => setPayoutMethod(event.target.value as typeof payoutMethod)}><option value="bank_transfer">تحويل بنكي</option><option value="cash_plus">Cash Plus</option><option value="wafacash">وفاكاش</option></select><Button type="submit" disabled={requestPayout.isPending}>طلب سحب المستحقات</Button></form></section>
    {showForm && <form onSubmit={submit} className="space-y-5 rounded-3xl border bg-card p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><input className="rounded-xl border bg-background p-3" placeholder="اسم المكتب" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><input className="rounded-xl border bg-background p-3" placeholder="المدينة" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /><select className="rounded-xl border bg-background p-3" value={form.officeType} onChange={(e) => setForm({ ...form, officeType: e.target.value })}>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select className="rounded-xl border bg-background p-3" value={form.rentalPeriod} onChange={(e) => setForm({ ...form, rentalPeriod: e.target.value })}><option value="daily">يومي</option><option value="monthly">شهري</option><option value="yearly">سنوي</option></select><input type="number" min="0" className="rounded-xl border bg-background p-3" placeholder="السعر بالدرهم" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /><textarea className="rounded-xl border bg-background p-3 md:col-span-2" placeholder="وصف المكتب" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex flex-wrap gap-2">{[["fiber", "Fiber Optic"], ["ac", "مكيف"], ["parking", "Parking"], ["security", "حراسة"]].map(([value, label]) => <button type="button" key={value} onClick={() => toggleAmenity(value)} className={`rounded-full border px-4 py-2 text-sm ${form.amenities.includes(value) ? "border-amber-500 bg-amber-50 text-amber-800" : "bg-background"}`}>{label}</button>)}</div><AdvancedMediaUpload onImagesUploaded={(urls) => setForm((current) => ({ ...current, imageUrl: urls[0] ?? "" }))} /><Button type="submit" disabled={createListing.isPending}>{createListing.isPending ? "جاري الحفظ..." : "إرسال المكتب للمراجعة"}</Button></form>}
    <section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">معروضاتي</h2><span className="text-sm text-muted-foreground">{listings.data?.length ?? 0} عروض</span></div>{listings.data?.length ? listings.data.map((listing) => { const isAvailable = listing.status === "Published" || listing.status === "Available"; return <div key={listing.id} className="flex flex-col gap-4 rounded-2xl border bg-card p-5 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{listing.title}</p><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${isAvailable ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{isAvailable ? "متاح" : "غير متاح"}</span></div><p className="mt-1 text-sm text-muted-foreground">{listing.city} · {Number(listing.pricePerDay).toLocaleString("fr-MA")} MAD · {listing.category === "car" ? "سيارة" : "عقار"}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Eye className="h-3.5 w-3.5" />{listing.analytics.views} مشاهدة</span><span className="inline-flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5" />{listing.analytics.whatsappClicks} واتساب</span><span className="inline-flex items-center gap-1"><Phone className="h-3.5 w-3.5" />{listing.analytics.contactClicks} اتصال</span></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={isAvailable ? "outline" : "default"} onClick={() => toggleAvailability.mutate({ listingId: listing.id, available: !isAvailable })} disabled={toggleAvailability.isPending}><Power className="ml-1 h-4 w-4" />{isAvailable ? "تعطيل التوفر" : "تفعيل التوفر"}</Button><Button size="sm" variant="outline" onClick={() => { setEditingId(listing.id); setForm({ title: listing.title, city: listing.city, officeType: listing.officeType ?? "office", rentalPeriod: listing.rentalPeriod ?? "monthly", price: String(listing.pricePerDay), description: listing.description ?? "", amenities: listing.amenities ? listing.amenities.split(",").filter(Boolean) : [], imageUrl: listing.imageUrl ?? "" }); setShowForm(true); }}><Pencil className="ml-1 h-4 w-4" />تعديل</Button><Button size="sm" variant="outline" onClick={() => removeListing.mutate({ id: listing.id })} disabled={removeListing.isPending}><Trash2 className="ml-1 h-4 w-4" />حذف</Button>{bookingContactHref(bookings.data, listing.id) && <a className="inline-flex items-center rounded-md border px-3 py-2 text-sm" href={bookingContactHref(bookings.data, listing.id)!} target="_blank" rel="noreferrer"><MessageCircle className="ml-1 h-4 w-4" />واتساب</a>}</div></div>; }) : <div className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">لم تضف أي معروض بعد.</div>}</section>
    <section className="space-y-4"><h2 className="text-xl font-bold">تقويم التوفر</h2>{listings.data?.map((listing) => <div key={`availability-${listing.id}`} className="rounded-2xl border bg-card p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{listing.title}</p><p className="text-sm text-muted-foreground">الفترات المحجوبة: {listing.availability ? JSON.parse(listing.availability).length : 0}</p></div><Button size="sm" onClick={() => { const current = listing.availability ? JSON.parse(listing.availability) : []; if (!availabilityDraft.start || !availabilityDraft.end) return toast.error("حدد تاريخ البداية والنهاية"); setAvailability.mutate({ listingId: listing.id, blockedRanges: [...current, { start: availabilityDraft.start, end: availabilityDraft.end }] }); }} disabled={setAvailability.isPending || availabilityDraft.listingId !== listing.id}><CalendarCheck className="ml-1 h-4 w-4" />حفظ الفترة</Button></div><div className="grid gap-3 sm:grid-cols-2"><input type="date" className="rounded-xl border bg-background p-3" aria-label="تاريخ بداية عدم التوفر" value={availabilityDraft.listingId === listing.id ? availabilityDraft.start : ""} onChange={(e) => setAvailabilityDraft({ listingId: listing.id, start: e.target.value, end: availabilityDraft.listingId === listing.id ? availabilityDraft.end : "" })} /><input type="date" className="rounded-xl border bg-background p-3" aria-label="تاريخ نهاية عدم التوفر" value={availabilityDraft.listingId === listing.id ? availabilityDraft.end : ""} onChange={(e) => setAvailabilityDraft({ listingId: listing.id, start: availabilityDraft.listingId === listing.id ? availabilityDraft.start : "", end: e.target.value })} /></div></div>)}</section>
    <section className="space-y-4"><h2 className="text-xl font-bold">مزامنة التقويم الخارجي (iCal)</h2><p className="text-sm text-muted-foreground">الصق رابط iCal الخاص بإعلانك من Airbnb أو Booking.com لاستيراد الفترات المحجوبة. رابط التصدير يمكن إضافته داخل المنصة الخارجية.</p>{listings.data?.map((listing) => <div key={`ical-${listing.id}`} className="rounded-2xl border bg-card p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{listing.title}</p><p className="text-sm text-muted-foreground">الحالة: {listing.icalSyncStatus === "ok" ? "متزامن" : listing.icalSyncStatus === "error" ? `خطأ: ${listing.icalSyncError ?? "تعذر الجلب"}` : "لم تتم المزامنة بعد"}{listing.icalLastSyncedAt ? ` · آخر تحديث ${new Date(listing.icalLastSyncedAt).toLocaleString("fr-MA")}` : ""}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => syncIcal.mutate({ listingId: listing.id })} disabled={syncIcal.isPending}><RefreshCw className="ml-1 h-4 w-4" />مزامنة الآن</Button></div></div><div className="grid gap-3 md:grid-cols-[1fr_auto]"><input dir="ltr" className="rounded-xl border bg-background p-3 text-left" placeholder="https://.../calendar.ics" value={icalDrafts[listing.id] ?? listing.icalImportUrl ?? ""} onChange={(event) => setIcalDrafts((current) => ({ ...current, [listing.id]: event.target.value }))} /><Button onClick={() => saveIcal.mutate({ listingId: listing.id, importUrl: (icalDrafts[listing.id] ?? listing.icalImportUrl ?? "").trim() || null })} disabled={saveIcal.isPending}>حفظ الرابط</Button></div>{listing.icalExportToken && <div className="mt-3 flex flex-col gap-2 rounded-xl bg-muted/50 p-3 text-sm"><span>رابط تصدير حجوزات B2-Rent:</span><div className="flex items-center gap-2"><code dir="ltr" className="min-w-0 flex-1 overflow-x-auto text-xs">{`${window.location.origin}/api/ical/export/${listing.icalExportToken}`}</code><Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(`${window.location.origin}/api/ical/export/${listing.icalExportToken}`)}><Copy className="ml-1 h-4 w-4" />نسخ</Button></div></div>}</div>)}</section>
    <section className="space-y-4"><h2 className="text-xl font-bold">طلبات الحجز</h2>{bookings.data?.length ? bookings.data.map((booking) => <div key={booking.id} className="flex flex-col gap-4 rounded-2xl border bg-card p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-bold">{booking.listingTitle ?? "مكتب"}</p><p className="text-sm text-muted-foreground">{booking.renterName ?? "مستأجر"} · {booking.status} · {Number(booking.totalPrice ?? 0).toLocaleString("fr-MA")} MAD</p></div>{booking.status === "Pending" && <div className="flex gap-2"><Button size="sm" onClick={() => updateStatus.mutate({ bookingId: booking.id, status: "Confirmed" })}><Check className="ml-1 h-4 w-4" />قبول</Button><Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ bookingId: booking.id, status: "Cancelled" })}><X className="ml-1 h-4 w-4" />رفض</Button></div>}</div>) : <div className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">لا توجد حجوزات واردة حالياً.</div>}</section>
  </div>;
}

function bookingContactHref(rows: Array<{ listingId: number; renterName?: string | null; status: string }> | undefined, listingId: number) { const booking = rows?.find((item) => item.listingId === listingId && item.status === "Confirmed"); return booking ? `https://wa.me/?text=${encodeURIComponent(`مرحباً، بخصوص حجز ${booking.renterName ?? "المستأجر"} في هذا المكتب`)}` : null; }
function Stat({ icon, title, value }: { icon?: React.ReactNode; title: string; value: string }) { return <div className="rounded-2xl border bg-card p-5"><div className="mb-3 flex items-center gap-2 text-[var(--brand-amber)]">{icon}<span className="text-sm text-muted-foreground">{title}</span></div><strong className="text-2xl">{value}</strong></div>; }
