import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ar" | "fr" | "en";

interface LanguageContextType {
  language: Language;
  direction: "rtl" | "ltr";
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    home: "الرئيسية",
    cars: "تأجير السيارات",
    properties: "العقارات",
    search: "البحث والعروض",
    admin: "لوحة الإدارة",
    dashboard: "لوحة الوكالة",
    addCar: "إضافة إعلان",
    myBookings: "حجوزاتي",
    favorites: "المفضلة",
    profile: "الملف الشخصي",
    account: "حسابي",
    partnerArea: "الشركاء ولوحات التحكم",
    help: "الدعم والمساعدة",
    about: "عن المنصة",
    blog: "المدونة",
    notifications: "الإشعارات",
    kyc: "التحقق من الهوية",
    heroTitle: "بوابتك الموثوقة لحجز السيارات والعقارات في المغرب",
    heroSubtitle: "اكتشف عروضاً مختارة من وكالات موثوقة، واحجز بسهولة مع عقود رقمية وفوترة شفافة.",
    aiSearchPlaceholder: "مثال: أريد سيارة دفع رباعي في أكادير أو شقة فاخرة في مراكش...",
    searchNow: "ابحث الآن",
    bookNow: "احجز الآن",
    viewDetails: "عرض التفاصيل",
    city: "المدينة",
    propertyType: "نوع العقار",
    price: "السعر",
    dates: "التواريخ",
    language: "اللغة",
    currency: "العملة",
    chooseLanguage: "اختيار اللغة",
    arabic: "العربية",
    french: "Français",
    switchArabic: "التبديل إلى العربية",
    switchFrench: "Passer au français",
    cmiPayment: "الدفع عبر CMI",
    bankTransfer: "التحويل البنكي",
    invoice: "الفاتورة",
    vat: "TVA",
    kycTitle: "تحقق من هويتك بأمان",
    kycSubtitle: "ارفع بطاقة التعريف الوطنية أو السجل التجاري ليتمكن فريقنا من مراجعة حسابك.",
    cni: "بطاقة التعريف الوطنية",
    commercialRegister: "السجل التجاري",
    submitDocument: "إرسال الوثيقة للمراجعة",
    pendingReview: "قيد المراجعة",
    approved: "تم التحقق",
    rejected: "مرفوضة",
    selectFile: "اختر ملفاً",
    noFile: "لم يتم اختيار ملف",
    maxFile: "PDF أو JPG أو PNG، بحد أقصى 8 ميغابايت",
    save: "حفظ",
    cancel: "إلغاء",
    close: "إغلاق",
    back: "رجوع",
    loading: "جاري التحميل...",
    allRights: "جميع الحقوق محفوظة",
    officeSpaces: "مساحات الأعمال",
    officeType: "نوع المساحة",
    privateOffice: "مكتب مستقل",
    coworking: "مساحة عمل مشتركة",
    meetingRoom: "قاعة اجتماعات",
    companyHeadquarters: "مقر شركة",
    rentalType: "نوع الكراء",
    daily: "يومي",
    monthly: "شهري",
    yearly: "سنوي",
    amenities: "التجهيزات والخدمات",
    fiber: "إنترنت Fiber Optic",
    airConditioning: "مكيف هواء",
    reception: "قاعة استقبال",
    parking: "مرآب Parking",
    security: "حراسة",
    all: "الكل",
    resultsFound: "عرض متاح",
    officeOnly: "المكاتب فقط",
    allSectors: "كل القطاعات",
    detailsAndBooking: "التفاصيل والحجز",
    resetFilters: "إعادة ضبط",
    advancedFilters: "تصفية متقدمة",
    naturalSearch: "بحث ذكي باللغة الطبيعية",
    searchPlaceholder: "ابحث عما ترغب به...",
    sector: "القطاع",
    carsOnly: "السيارات فقط",
    propertiesOnly: "العقارات فقط",
    maxPrice: "السعر الأقصى",
    allCities: "جميع المدن",
    offersFoundPrefix: "تم العثور على",
    sortBy: "الترتيب حسب",
    lowestPrice: "السعر: من الأرخص للأغلى",
    highestPrice: "السعر: من الأغلى للأرخص",
    loadingListings: "جاري تحميل العروض",
    listingsLoadError: "تعذر تحميل العروض حالياً. يرجى المحاولة مرة أخرى بعد قليل.",
    noMatchingListings: "لا توجد عروض مطابقة للفلاتر الحالية. جرّب توسيع المدينة أو السعر أو نوع المكتب.",
    showMap: "عرض الخريطة التفاعلية",
    hideMap: "إخفاء الخريطة التفاعلية",
    availableOffers: "عرض متاح",

    demoBadge: "نسخة تجريبية",
    demoBadgeTitle: "نسخة تجريبية قيد التطوير",
    brandHomeAria: "B2-Rent Morocco — العودة إلى الصفحة الرئيسية",
    primaryNavigation: "التنقل الرئيسي",
    mobileNavigation: "التنقل على الهاتف",
    roleAdmin: "مشرف عام",
    roleAgency: "مدير وكالة",
    accountSecurity: "أمان الحساب",
    whatsappSms: "WhatsApp / SMS",
    dayMode: "الوضع النهاري",
    nightMode: "الوضع الليلي",
    currencyChanged: "تم تبديل العملة بنجاح إلى {currency}",
    languageChanged: "تم التبديل إلى اللغة العربية",
    dayModeEnabled: "تم تفعيل الوضع النهاري",
    nightModeEnabled: "تم تفعيل الوضع الليلي",
    notificationAria: "الإشعارات",
    unreadNotifications: "غير مقروءة",
    notificationList: "قائمة الإشعارات",
    notificationUpdates: "الإشعارات والتحديثات",
    notificationSoundOff: "إيقاف صوت الإشعارات",
    notificationSoundOn: "تفعيل صوت الإشعارات",
    soundEnabled: "الصوت مفعّل",
    soundDisabled: "الصوت متوقف",
    markAllRead: "تحديد الكل كمقروء",
    updating: "جارٍ التحديث…",
    loginToNotifications: "سجّل الدخول لمتابعة إشعارات حجوزاتك.",
    noNewNotifications: "لا توجد إشعارات جديدة.",
    allNotifications: "عرض كل الإشعارات",
    mobileSearch: "فتح البحث",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    english: "English",
    switchEnglish: "التبديل إلى الإنجليزية",
    car: "سيارة",
    property: "عقار",
    listingProvider: "بيانات الإعلان من B2-Rent",
    cityCasablanca: "الدار البيضاء",
    cityMarrakech: "مراكش",
    cityAgadir: "أغادير",
    cityTangier: "طنجة",
    cityRabat: "الرباط",
    cityCasablancaHelper: "الأعمال والإقامات",
    cityMarrakechHelper: "المدينة الحمراء",
    cityTangierHelper: "البوابة الشمالية",
    cityAgadirHelper: "الساحل والرحلات",
    airportMohammedV: "مطار محمد الخامس",
    airportMohammedVHelper: "ضمن نطاق الدار البيضاء",
    apartments: "شقق",
    villas: "فيلات",
    offices: "مكاتب",
    studios: "استوديوهات",
    browseRailAria: "علامات السيارات وفئات العقارات",
    cityMarrakechAreas: "مراكش (جيليز، النخيل)",
    cityCasablancaAreas: "الدار البيضاء (أنفا، المعاريف)",
    cityTangierAreas: "طنجة (كورنيش، مالاباطا)",
    cityRabatAreas: "الرباط (أكدال، السويسي)",
    apartmentOption: "شقة فاخرة",
    villaOption: "فيلا بمسبح",
    studioOption: "استوديو مودرن",
    under1000: "أقل من 1000 درهم",
    under2500: "أقل من 2500 درهم",
    under5000: "أقل من 5000 درهم",
    over5000: "أكثر من 5000 درهم",
    browseByNeed: "تصفح حسب احتياجك",
    balancedSearchTitle: "سيارات وعقارات، بتجربة بحث متوازنة",
    carBrands: "ماركات السيارات",
    allCars: "كل السيارات",
    propertyTypes: "أنواع العقارات",
    allProperties: "كل العقارات",
    advancedDesign: "تصميم هندسي متطور",
    exploreMainSections: "استكشف الأقسام الرئيسية",
    bentoSubtitle: "اختر ما بين أسطول السيارات الفاخرة أو العقارات الحصرية مع ضمانات حماية كاملة.",
    carFleetTitle: "أسطول السيارات الفاخرة والاقتصادية",
    carFleetDescription: "أحدث موديلات سيارات الدفع الرباعي، السيارات العائلية، والسيارات الرياضية في الدار البيضاء، مراكش، طنجة وأغادير مع توصيل مجاني.",
    browseCars: "تصفح السيارات المتاحة",
    propertyTitle: "العقارات والشقق الفاخرة",
    propertyDescription: "شقق مودرن مطلة على الكورنيش وفيلات خاصة بمسبح في أرقى الأحياء السكنية.",
    browseProperties: "تصفح العقارات",
    availableListingsEyebrow: "إعلانات متاحة للتصفح",
    featuredListings: "إعلانات مختارة من المنصة",
    viewAllListings: "عرض كافة الإعلانات",
    dailyPrice: "السعر اليومي",
    demoDetails: "عرض التفاصيل التجريبية",
    blogEyebrow: "مدونة المنصة",
    latestArticles: "أحدث المقالات والنصائح العقارية والسياحية",
    browseAllArticles: "تصفح جميع المقالات",
    travelGuide: "دليل السفر",
    travelGuideTitle: "دليلك الشامل لكراء السيارات في الدار البيضاء ومراكش 2026",
    travelGuideDescription: "تعرف على أهم النصائح القانونية والتقنية لتأجير السيارات بكل أمان في المدن الكبرى بالمغرب.",
    realEstateInvestment: "استثمار عقاري",
    realEstateInvestmentTitle: "أفضل المناطق الاستثمارية العقارية في طنجة وأغادير",
    realEstateInvestmentDescription: "استعراض لأهم الأحياء المطلة على البحر والتي تشهد إقبالاً كبيراً من السياح والمستثمرين.",
    drivingTips: "نصائح قيادة",
    drivingTipsTitle: "كيف تختار السيارة المناسبة لرحلتك العائلية عبر الطرق السيارة؟",
    drivingTipsDescription: "مقارنة شاملة بين سيارات الـ SUV والاقتصادية والفاخرة لضمان أقصى درجات الراحة والأمان.",
    readMore: "اقرأ المزيد",
    securePaymentTitle: "حماية ودفع آمن 100%",
    securePaymentDescription: "بوابات دفع معتمدة وعقود رقمية مختومة قانونياً.",
    trustedAgenciesTitle: "وكالات معتمدة وموثوقة",
    trustedAgenciesDescription: "مراجعة وتدقيق دوري لجميع شركائنا في المغرب.",
    supportTitle: "دعم فني على مدار الساعة",
    supportDescription: "فريق خدمة عملاء متواجد دائماً لمساعدتك.",
    carFleetAlt: "أسطول السيارات",
    propertyAlt: "عقارات وشقق",
    carRentalAlt: "كراء السيارات",
    realEstateAlt: "العقارات",
    drivingAlt: "نصائح القيادة",
    listingNumber: "الإعلان رقم {id}",
    propertyDetails: "تفاصيل العقار",
    carDetails: "تفاصيل السيارة",
    listingDetails: "تفاصيل الإعلان",
    breadcrumb: "مسار التنقل",
    allNotificationsRead: "تم تحديد جميع الإشعارات كمقروءة",
    checkout: "إتمام الدفع",
    success: "تأكيد الحجز",
    disputeResolution: "حل النزاعات",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الاستخدام",
    listingPage: "صفحة الإعلان",
    faqBadge: "الأسئلة المتكررة",
    faqTitle: "كل ما ترغب في معرفته حول خدمات B2-Rent",
    faqSubtitle: "إجابات شاملة وواضحة عن عمليات الحجز والدفع وحقوق الشركاء والزبناء في المغرب.",
    faqRentalsCategory: "التأجير والحجوزات",
    faqRentalsQuestion: "كيف يمكنني حجز سيارة أو عقار عبر منصة B2-Rent؟",
    faqRentalsAnswer: "يمكنك بكل سهولة تصفح السيارات أو العقارات المتاحة، اختيار تواريخ الاستلام والتسليم، ثم الضغط على 'احجز الآن'. سيتم توجيهك لملء تفاصيل الحجز وإتمام الدفع الآمن لعربون الضمان عبر بواباتنا المعتمدة.",
    faqSecurityCategory: "الأمان والضمان",
    faqSecurityQuestion: "هل المعاملات المالية وعربون الحجز آمنان؟",
    faqSecurityAnswer: "نعم تماماً. تعتمد منصة B2-Rent نظام ضمان مالي (Escrow) حيث تبقى أموال العربون في حساب الوسيط المعتمد حتى يتم تأكيد استلام السيارة أو العقار بحالة ممتازة من طرف الشريك.",
    faqPartnersCategory: "الشركاء والوكالات",
    faqPartnersQuestion: "كيف يمكنني تسجيل شركتي أو عقاري كشريك في المنصة؟",
    faqPartnersAnswer: "يمكنك الانتقال إلى صفحة 'لوحة الوكلاء' واختيار التسجيل كشركة كراء سيارات أو منعش عقاري، رفع وثائق التحقق (السجل التجاري أو البطاقة الوطنية)، وبعد مراجعة الإدارة سيتم تفعيل حسابك فوراً.",
    faqCancellationCategory: "سياسة الإلغاء",
    faqCancellationQuestion: "ما هي سياسة إلغاء الحجوزات واسترداد العربون؟",
    faqCancellationAnswer: "يمكنك إلغاء الحجز مجاناً قبل موعد الاستلام بـ 48 ساعة واسترداد كامل العربون المدفوع. للإلغاء المتأخر، يتم تطبيق شروط الوكالة المتعاقد معها والموضحة في العقد الرقمي.",
  },
  fr: {
    home: "Accueil",
    cars: "Location de voitures",
    properties: "Immobilier",
    search: "Recherche et offres",
    admin: "Administration",
    dashboard: "Tableau de bord agence",
    addCar: "Ajouter une annonce",
    myBookings: "Mes réservations",
    favorites: "Favoris",
    profile: "Profil",
    account: "Mon compte",
    partnerArea: "Partenaires et espaces de gestion",
    help: "Aide et support",
    about: "À propos",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Vérification d'identité",
    heroTitle: "Votre passerelle de confiance pour louer voitures et biens au Maroc",
    heroSubtitle: "Découvrez des offres sélectionnées auprès d'agences fiables, réservez simplement avec contrats numériques et facturation transparente.",
    aiSearchPlaceholder: "Exemple : je veux un SUV à Agadir ou un appartement de luxe à Marrakech...",
    searchNow: "Rechercher",
    bookNow: "Réserver maintenant",
    viewDetails: "Voir les détails",
    city: "Ville",
    propertyType: "Type de bien",
    price: "Prix",
    dates: "Dates",
    language: "Langue",
    currency: "Devise",
    chooseLanguage: "Choisir la langue",
    arabic: "العربية",
    french: "Français",
    switchArabic: "التبديل إلى العربية",
    switchFrench: "Passer au français",
    cmiPayment: "Paiement CMI",
    bankTransfer: "Virement bancaire",
    invoice: "Facture",
    vat: "TVA",
    kycTitle: "Vérifiez votre identité en toute sécurité",
    kycSubtitle: "Téléversez votre CNI ou registre de commerce pour permettre à notre équipe de vérifier votre compte.",
    cni: "Carte nationale d'identité",
    commercialRegister: "Registre de commerce",
    submitDocument: "Envoyer le document pour vérification",
    pendingReview: "En cours de vérification",
    approved: "Identité vérifiée",
    rejected: "Document refusé",
    selectFile: "Choisir un fichier",
    noFile: "Aucun fichier sélectionné",
    maxFile: "PDF, JPG ou PNG, 8 Mo maximum",
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    back: "Retour",
    loading: "Chargement...",
    allRights: "Tous droits réservés",
    officeSpaces: "Espaces professionnels",
    officeType: "Type d'espace",
    privateOffice: "Bureau indépendant",
    coworking: "Espace coworking",
    meetingRoom: "Salle de réunion",
    companyHeadquarters: "Siège d'entreprise",
    rentalType: "Type de location",
    daily: "Journalier",
    monthly: "Mensuel",
    yearly: "Annuel",
    amenities: "Équipements et services",
    fiber: "Internet Fiber Optic",
    airConditioning: "Climatisation",
    reception: "Accueil",
    parking: "Parking",
    security: "Sécurité",
    all: "Tous",
    resultsFound: "offre(s) disponible(s)",
    officeOnly: "Bureaux uniquement",
    allSectors: "Tous les secteurs",
    detailsAndBooking: "Détails et réservation",
    resetFilters: "Réinitialiser",
    advancedFilters: "Filtres avancés",
    naturalSearch: "Recherche intelligente en langage naturel",
    searchPlaceholder: "Recherchez ce dont vous avez besoin...",
    sector: "Secteur",
    carsOnly: "Voitures uniquement",
    propertiesOnly: "Biens uniquement",
    maxPrice: "Prix maximum",
    allCities: "Toutes les villes",
    offersFoundPrefix: "Résultat :",
    sortBy: "Trier par",
    lowestPrice: "Prix : du moins cher au plus cher",
    highestPrice: "Prix : du plus cher au moins cher",
    loadingListings: "Chargement des offres",
    listingsLoadError: "Les offres sont momentanément indisponibles. Veuillez réessayer.",
    noMatchingListings: "Aucune offre ne correspond aux filtres actuels. Élargissez la ville, le prix ou le type de bureau.",
    showMap: "Afficher la carte interactive",
    hideMap: "Masquer la carte interactive",
    availableOffers: "offre(s) disponible(s)",

    demoBadge: "Version démo",
    demoBadgeTitle: "Version de démonstration en développement",
    brandHomeAria: "B2-Rent Morocco — retour à l'accueil",
    primaryNavigation: "Navigation principale",
    mobileNavigation: "Navigation mobile",
    roleAdmin: "Super administrateur",
    roleAgency: "Responsable d'agence",
    accountSecurity: "Sécurité du compte",
    whatsappSms: "WhatsApp / SMS",
    dayMode: "Mode clair",
    nightMode: "Mode sombre",
    currencyChanged: "Devise changée avec succès : {currency}",
    languageChanged: "Français activé",
    dayModeEnabled: "Mode clair activé",
    nightModeEnabled: "Mode sombre activé",
    notificationAria: "Notifications",
    unreadNotifications: "non lues",
    notificationList: "Liste des notifications",
    notificationUpdates: "Notifications et mises à jour",
    notificationSoundOff: "Désactiver le son des notifications",
    notificationSoundOn: "Activer le son des notifications",
    soundEnabled: "Son activé",
    soundDisabled: "Son désactivé",
    markAllRead: "Tout marquer comme lu",
    updating: "Mise à jour…",
    loginToNotifications: "Connectez-vous pour suivre vos notifications de réservation.",
    noNewNotifications: "Aucune nouvelle notification.",
    allNotifications: "Voir toutes les notifications",
    mobileSearch: "Ouvrir la recherche",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    english: "English",
    switchEnglish: "Passer à l'anglais",
    car: "voiture",
    property: "bien",
    listingProvider: "Données de l'annonce B2-Rent",
    cityCasablanca: "Casablanca",
    cityMarrakech: "Marrakech",
    cityAgadir: "Agadir",
    cityTangier: "Tanger",
    cityRabat: "Rabat",
    cityCasablancaHelper: "Affaires et séjours",
    cityMarrakechHelper: "La ville rouge",
    cityTangierHelper: "Porte du Nord",
    cityAgadirHelper: "Côte et escapades",
    airportMohammedV: "Aéroport Mohammed V",
    airportMohammedVHelper: "Dans la zone de Casablanca",
    apartments: "Appartements",
    villas: "Villas",
    offices: "Bureaux",
    studios: "Studios",
    browseRailAria: "Marques automobiles et catégories immobilières",
    cityMarrakechAreas: "Marrakech (Guéliz, Palmeraie)",
    cityCasablancaAreas: "Casablanca (Anfa, Maârif)",
    cityTangierAreas: "Tanger (Corniche, Malabata)",
    cityRabatAreas: "Rabat (Agdal, Souissi)",
    apartmentOption: "Appartement premium",
    villaOption: "Villa avec piscine",
    studioOption: "Studio moderne",
    under1000: "Moins de 1 000 MAD",
    under2500: "Moins de 2 500 MAD",
    under5000: "Moins de 5 000 MAD",
    over5000: "Plus de 5 000 MAD",
    browseByNeed: "Parcourir selon votre besoin",
    balancedSearchTitle: "Voitures et immobilier, une recherche équilibrée",
    carBrands: "Marques automobiles",
    allCars: "Toutes les voitures",
    propertyTypes: "Types de biens",
    allProperties: "Tous les biens",
    advancedDesign: "Design de recherche avancé",
    exploreMainSections: "Explorez les sections principales",
    bentoSubtitle: "Choisissez entre une flotte automobile premium et des biens exclusifs, avec des garanties de protection complètes.",
    carFleetTitle: "Flotte de voitures premium et économiques",
    carFleetDescription: "Les derniers SUV, modèles familiaux et voitures sportives à Casablanca, Marrakech, Tanger et Agadir, avec livraison gratuite.",
    browseCars: "Parcourir les voitures disponibles",
    propertyTitle: "Biens et appartements premium",
    propertyDescription: "Appartements modernes en bord de mer et villas privées avec piscine dans les quartiers les plus recherchés.",
    browseProperties: "Parcourir les biens",
    availableListingsEyebrow: "Annonces à découvrir",
    featuredListings: "Annonces sélectionnées sur la plateforme",
    viewAllListings: "Voir toutes les annonces",
    dailyPrice: "Prix journalier",
    demoDetails: "Voir les détails de la démo",
    blogEyebrow: "Blog de la plateforme",
    latestArticles: "Derniers articles et conseils voyage et immobilier",
    browseAllArticles: "Voir tous les articles",
    travelGuide: "Guide de voyage",
    travelGuideTitle: "Votre guide de la location de voitures à Casablanca et Marrakech en 2026",
    travelGuideDescription: "Les conseils juridiques et pratiques essentiels pour louer une voiture en toute sécurité dans les grandes villes du Maroc.",
    realEstateInvestment: "Investissement immobilier",
    realEstateInvestmentTitle: "Les meilleurs quartiers d'investissement à Tanger et Agadir",
    realEstateInvestmentDescription: "Tour d'horizon des quartiers en bord de mer qui attirent touristes et investisseurs.",
    drivingTips: "Conseils de conduite",
    drivingTipsTitle: "Comment choisir la voiture idéale pour un voyage familial sur autoroute ?",
    drivingTipsDescription: "Comparatif des SUV, voitures économiques et premium pour un confort et une sécurité maximaux.",
    readMore: "Lire la suite",
    securePaymentTitle: "Protection et paiement sécurisé à 100 %",
    securePaymentDescription: "Des moyens de paiement reconnus et des contrats numériques juridiquement scellés.",
    trustedAgenciesTitle: "Agences fiables et vérifiées",
    trustedAgenciesDescription: "Un contrôle régulier de nos partenaires partout au Maroc.",
    supportTitle: "Support technique disponible 24h/24",
    supportDescription: "Une équipe de service client toujours disponible pour vous accompagner.",
    carFleetAlt: "Flotte automobile",
    propertyAlt: "Biens et appartements",
    carRentalAlt: "Location de voitures",
    realEstateAlt: "Immobilier",
    drivingAlt: "Conseils de conduite",
    listingNumber: "Annonce n° {id}",
    propertyDetails: "Détails du bien",
    carDetails: "Détails de la voiture",
    listingDetails: "Détails de l'annonce",
    breadcrumb: "Fil d'Ariane",
    allNotificationsRead: "Toutes les notifications sont marquées comme lues",
    checkout: "Paiement",
    success: "Confirmation de réservation",
    disputeResolution: "Résolution des litiges",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    listingPage: "Annonce",
    faqBadge: "Questions fréquentes",
    faqTitle: "Tout savoir sur les services B2-Rent",
    faqSubtitle: "Des réponses claires sur les réservations, les paiements et les droits des partenaires et clients au Maroc.",
    faqRentalsCategory: "Location et réservations",
    faqRentalsQuestion: "Comment réserver une voiture ou un bien sur B2-Rent ?",
    faqRentalsAnswer: "Parcourez les voitures ou les biens disponibles, choisissez les dates de prise en charge et de restitution, puis cliquez sur « Réserver maintenant ». Vous pourrez renseigner les détails de la réservation et effectuer le paiement sécurisé de l'acompte via nos moyens agréés.",
    faqSecurityCategory: "Sécurité et garantie",
    faqSecurityQuestion: "Les transactions et l'acompte de réservation sont-ils sécurisés ?",
    faqSecurityAnswer: "Oui. B2-Rent prévoit un mécanisme de garantie (Escrow) : l'acompte reste auprès de l'intermédiaire agréé jusqu'à la confirmation de la remise de la voiture ou du bien par le partenaire.",
    faqPartnersCategory: "Partenaires et agences",
    faqPartnersQuestion: "Comment inscrire mon entreprise ou mon bien comme partenaire ?",
    faqPartnersAnswer: "Accédez à l’espace agence, choisissez l’inscription comme société de location ou professionnel de l’immobilier, puis envoyez les justificatifs demandés (registre de commerce ou pièce d’identité). L’activation intervient après vérification par l’administration.",
    faqCancellationCategory: "Politique d'annulation",
    faqCancellationQuestion: "Quelle est la politique d'annulation et de remboursement de l'acompte ?",
    faqCancellationAnswer: "Vous pouvez annuler gratuitement jusqu'à 48 heures avant la remise et récupérer l'acompte payé. En cas d'annulation tardive, les conditions de l'agence indiquées dans le contrat numérique s'appliquent.",
  },
  en: {
    home: "Home",
    cars: "Car rentals",
    properties: "Properties",
    search: "Search & listings",
    admin: "Admin dashboard",
    dashboard: "Agency dashboard",
    addCar: "Add listing",
    myBookings: "My bookings",
    favorites: "Favorites",
    profile: "Profile",
    account: "My account",
    partnerArea: "Partners & management areas",
    help: "Help & support",
    about: "About B2-Rent",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Identity verification",
    heroTitle: "Your trusted gateway to car and property rentals in Morocco",
    heroSubtitle: "Discover carefully selected offers from trusted agencies, with easy booking, digital contracts, and transparent billing.",
    aiSearchPlaceholder: "Example: I want an SUV in Agadir or a luxury apartment in Marrakech...",
    searchNow: "Search now",
    bookNow: "Book now",
    viewDetails: "View details",
    city: "City",
    propertyType: "Property type",
    price: "Price",
    dates: "Dates",
    language: "Language",
    currency: "Currency",
    chooseLanguage: "Choose language",
    arabic: "العربية",
    french: "Français",
    english: "English",
    switchArabic: "Switch to Arabic",
    switchFrench: "Passer au français",
    switchEnglish: "Switch to English",
    cmiPayment: "CMI payment",
    bankTransfer: "Bank transfer",
    invoice: "Invoice",
    vat: "VAT",
    kycTitle: "Verify your identity securely",
    kycSubtitle: "Upload your national ID or commercial register so our team can review your account.",
    cni: "National identity card",
    commercialRegister: "Commercial register",
    submitDocument: "Submit document for review",
    pendingReview: "Under review",
    approved: "Verified",
    rejected: "Rejected",
    selectFile: "Choose a file",
    noFile: "No file selected",
    maxFile: "PDF, JPG, or PNG, up to 8 MB",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    loading: "Loading...",
    allRights: "All rights reserved",
    officeSpaces: "Business spaces",
    officeType: "Space type",
    privateOffice: "Private office",
    coworking: "Coworking space",
    meetingRoom: "Meeting room",
    companyHeadquarters: "Company headquarters",
    rentalType: "Rental period",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    amenities: "Amenities and services",
    fiber: "Fiber optic internet",
    airConditioning: "Air conditioning",
    reception: "Reception",
    parking: "Parking",
    security: "Security",
    all: "All",
    resultsFound: "available offer(s)",
    officeOnly: "Offices only",
    allSectors: "All sectors",
    detailsAndBooking: "Details and booking",
    resetFilters: "Reset filters",
    advancedFilters: "Advanced filters",
    naturalSearch: "Natural-language search",
    searchPlaceholder: "Search for what you need...",
    sector: "Sector",
    carsOnly: "Cars only",
    propertiesOnly: "Properties only",
    maxPrice: "Maximum price",
    allCities: "All cities",
    offersFoundPrefix: "Found",
    sortBy: "Sort by",
    lowestPrice: "Price: low to high",
    highestPrice: "Price: high to low",
    loadingListings: "Loading listings",
    listingsLoadError: "Listings are temporarily unavailable. Please try again.",
    noMatchingListings: "No listings match the current filters. Try widening the city, price, or office type.",
    showMap: "Show interactive map",
    hideMap: "Hide interactive map",
    availableOffers: "available offer(s)",

    demoBadge: "Demo version",
    demoBadgeTitle: "Demo version in development",
    brandHomeAria: "B2-Rent Morocco — back to home",
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    roleAdmin: "Super administrator",
    roleAgency: "Agency manager",
    accountSecurity: "Account security",
    whatsappSms: "WhatsApp / SMS",
    dayMode: "Light mode",
    nightMode: "Dark mode",
    currencyChanged: "Currency changed successfully to {currency}",
    languageChanged: "English enabled",
    dayModeEnabled: "Light mode enabled",
    nightModeEnabled: "Dark mode enabled",
    notificationAria: "Notifications",
    unreadNotifications: "unread",
    notificationList: "Notification list",
    notificationUpdates: "Notifications and updates",
    notificationSoundOff: "Turn notification sound off",
    notificationSoundOn: "Turn notification sound on",
    soundEnabled: "Sound on",
    soundDisabled: "Sound off",
    markAllRead: "Mark all as read",
    updating: "Updating…",
    loginToNotifications: "Sign in to follow your booking notifications.",
    noNewNotifications: "No new notifications.",
    allNotifications: "View all notifications",
    mobileSearch: "Open search",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    car: "car",
    property: "property",
    listingProvider: "Listing data from B2-Rent",
    cityCasablanca: "Casablanca",
    cityMarrakech: "Marrakech",
    cityAgadir: "Agadir",
    cityTangier: "Tangier",
    cityRabat: "Rabat",
    cityCasablancaHelper: "Business and stays",
    cityMarrakechHelper: "The red city",
    cityTangierHelper: "Northern gateway",
    cityAgadirHelper: "Coast and getaways",
    airportMohammedV: "Mohammed V Airport",
    airportMohammedVHelper: "Within the Casablanca area",
    apartments: "Apartments",
    villas: "Villas",
    offices: "Offices",
    studios: "Studios",
    browseRailAria: "Car brands and property categories",
    cityMarrakechAreas: "Marrakech (Gueliz, Palmeraie)",
    cityCasablancaAreas: "Casablanca (Anfa, Maarif)",
    cityTangierAreas: "Tangier (Corniche, Malabata)",
    cityRabatAreas: "Rabat (Agdal, Souissi)",
    apartmentOption: "Luxury apartment",
    villaOption: "Villa with pool",
    studioOption: "Modern studio",
    under1000: "Under MAD 1,000",
    under2500: "Under MAD 2,500",
    under5000: "Under MAD 5,000",
    over5000: "Over MAD 5,000",
    browseByNeed: "Browse by your need",
    balancedSearchTitle: "Cars and property, with a balanced search experience",
    carBrands: "Car brands",
    allCars: "All cars",
    propertyTypes: "Property types",
    allProperties: "All properties",
    advancedDesign: "Advanced search design",
    exploreMainSections: "Explore the main sections",
    bentoSubtitle: "Choose between a premium car fleet and exclusive properties, with complete protection assurances.",
    carFleetTitle: "Premium and economy car fleet",
    carFleetDescription: "The latest SUVs, family cars, and sport models in Casablanca, Marrakech, Tangier, and Agadir, with free delivery.",
    browseCars: "Browse available cars",
    propertyTitle: "Premium properties and apartments",
    propertyDescription: "Modern seaside apartments and private pool villas in Morocco's most sought-after neighbourhoods.",
    browseProperties: "Browse properties",
    availableListingsEyebrow: "Listings ready to explore",
    featuredListings: "Featured listings from the platform",
    viewAllListings: "View all listings",
    dailyPrice: "Daily price",
    demoDetails: "View demo details",
    blogEyebrow: "Platform blog",
    latestArticles: "Latest travel and real-estate articles and tips",
    browseAllArticles: "Browse all articles",
    travelGuide: "Travel guide",
    travelGuideTitle: "Your complete guide to car rental in Casablanca and Marrakech in 2026",
    travelGuideDescription: "Key legal and practical tips for renting cars safely in Morocco's major cities.",
    realEstateInvestment: "Real-estate investment",
    realEstateInvestmentTitle: "The best real-estate investment areas in Tangier and Agadir",
    realEstateInvestmentDescription: "A look at seaside neighbourhoods attracting strong interest from travellers and investors.",
    drivingTips: "Driving tips",
    drivingTipsTitle: "How do you choose the right car for a family road trip?",
    drivingTipsDescription: "A practical comparison of SUVs, economy cars, and premium models for comfort and safety.",
    readMore: "Read more",
    securePaymentTitle: "100% secure protection and payment",
    securePaymentDescription: "Recognised payment methods and legally sealed digital contracts.",
    trustedAgenciesTitle: "Trusted, verified agencies",
    trustedAgenciesDescription: "Regular review and verification of partners across Morocco.",
    supportTitle: "24/7 technical support",
    supportDescription: "A customer-care team always available to help.",
    carFleetAlt: "Car fleet",
    propertyAlt: "Properties and apartments",
    carRentalAlt: "Car rental",
    realEstateAlt: "Real estate",
    drivingAlt: "Driving tips",
    listingNumber: "Listing {id}",
    propertyDetails: "Property details",
    carDetails: "Car details",
    listingDetails: "Listing details",
    breadcrumb: "Breadcrumb",
    allNotificationsRead: "All notifications marked as read",
    checkout: "Checkout",
    success: "Booking confirmation",
    disputeResolution: "Dispute resolution",
    privacyPolicy: "Privacy policy",
    termsOfService: "Terms of service",
    listingPage: "Listing",
    faqBadge: "Frequently asked questions",
    faqTitle: "Everything you need to know about B2-Rent",
    faqSubtitle: "Clear answers about bookings, payments, and partner and customer rights in Morocco.",
    faqRentalsCategory: "Rentals and bookings",
    faqRentalsQuestion: "How can I book a car or property through B2-Rent?",
    faqRentalsAnswer: "Browse available cars or properties, choose the pickup and return dates, then select “Book now”. You will be guided through the booking details and secure deposit payment using our approved payment methods.",
    faqSecurityCategory: "Security and guarantee",
    faqSecurityQuestion: "Are financial transactions and the booking deposit secure?",
    faqSecurityAnswer: "Yes. B2-Rent provides a guarantee mechanism (Escrow): the deposit remains with the approved intermediary until the partner confirms that the car or property has been handed over.",
    faqPartnersCategory: "Partners and agencies",
    faqPartnersQuestion: "How can I register my company or property as a partner?",
    faqPartnersAnswer: "Open the agency area, choose registration as a car-rental company or real-estate professional, and submit the requested verification documents. Activation follows an administration review.",
    faqCancellationCategory: "Cancellation policy",
    faqCancellationQuestion: "What is the cancellation and deposit-refund policy?",
    faqCancellationAnswer: "You can cancel free of charge up to 48 hours before handover and recover the deposit paid. For late cancellation, the agency terms stated in the digital contract apply.",
  },
};

export const SUPPORTED_LANGUAGES = ["ar", "fr", "en"] as const;

export function getDirectionForLanguage(language: Language): "rtl" | "ltr" {
  return language === "ar" ? "rtl" : "ltr";
}

export function getLocaleForLanguage(language: Language) {
  return language === "ar" ? "ar-MA" : language === "fr" ? "fr-MA" : "en-GB";
}

export function getTranslation(language: Language, key: string) {
  return translations[language][key] ?? translations.en[key] ?? translations.ar[key] ?? key;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "ar";
    const saved = window.localStorage.getItem("b2rent-language");
    return saved === "fr" || saved === "en" ? saved : "ar";
  });

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("b2rent-language", nextLanguage);
  };

  const direction = getDirectionForLanguage(language);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    document.body.dir = direction;
  }, [direction, language]);

  const value = useMemo(() => ({
    language,
    direction,
    setLanguage,
    t: (key: string) => getTranslation(language, key),
  }), [direction, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}
