BEGIN;

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  open_id varchar(64) NOT NULL UNIQUE,
  name text,
  email varchar(320), whatsapp_phone varchar(32), commercial_register varchar(120), agency_name varchar(180), agency_logo_url text,
  agency_phone varchar(32), agency_email varchar(320), agency_address varchar(255), agency_website varchar(255), agency_latitude varchar(32), agency_longitude varchar(32), agency_hours text,
  login_method varchar(64), password_hash varchar(255), role varchar(16) NOT NULL DEFAULT 'user', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), last_signed_in timestamptz NOT NULL DEFAULT now(), legal_consent_version varchar(80), legal_consent_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.listings (
  listing_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id integer NOT NULL, title text NOT NULL, description text, category varchar(64) NOT NULL, price_per_day integer NOT NULL, image_url text,
  status varchar(16) NOT NULL DEFAULT 'Published', city varchar(64) NOT NULL DEFAULT 'الدار البيضاء', fuel_type varchar(32) DEFAULT 'ديزل', transmission varchar(32) DEFAULT 'أوتوماتيك', rooms integer DEFAULT 0, office_type varchar(64), rental_period varchar(16), amenities text, availability text, ical_import_url text, ical_export_token varchar(96) UNIQUE, ical_imported_ranges text, ical_last_synced_at timestamptz, ical_sync_status varchar(16) NOT NULL DEFAULT 'never', ical_sync_error varchar(500), created_at timestamptz NOT NULL DEFAULT now()
);

-- Reconcile the legacy public.bookings table without dropping or renaming legacy columns.
-- The application columns are nullable during acceptance so existing legacy rows remain valid.
CREATE TABLE IF NOT EXISTS public.bookings (
  booking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  renter_id integer,
  listing_id integer,
  secondary_listing_id integer,
  start_date timestamptz,
  end_date timestamptz,
  total_price integer,
  commission_fee integer,
  net_profit integer,
  status varchar(16) NOT NULL DEFAULT 'Pending',
  cancellation_policy_version varchar(80),
  cancellation_policy_snapshot text,
  cancellation_policy_fingerprint varchar(80),
  cancellation_policy_accepted_at timestamptz,
  cancellation_policy_accepted_by integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS booking_id integer GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS renter_id integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS listing_id integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS secondary_listing_id integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS start_date timestamptz;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS end_date timestamptz;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS total_price integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS commission_fee integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS net_profit integer;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS cancellation_policy_version varchar(80);
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS cancellation_policy_snapshot text;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS cancellation_policy_fingerprint varchar(80);
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS cancellation_policy_accepted_at timestamptz;
ALTER TABLE IF EXISTS public.bookings ADD COLUMN IF NOT EXISTS cancellation_policy_accepted_by integer;
CREATE UNIQUE INDEX IF NOT EXISTS bookings_booking_id_uidx ON public.bookings(booking_id);

CREATE TABLE IF NOT EXISTS public.listing_analytics_events (
  event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id integer NOT NULL, event_type varchar(32) NOT NULL, visitor_key varchar(128), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS listing_analytics_listing_event_idx ON public.listing_analytics_events(listing_id, event_type);
CREATE INDEX IF NOT EXISTS listing_analytics_listing_created_idx ON public.listing_analytics_events(listing_id, created_at);

CREATE TABLE IF NOT EXISTS public.reviews (
  review_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL, listing_id integer NOT NULL, user_id integer NOT NULL, rating integer NOT NULL, comment text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.kyc_submissions (
  kyc_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL, applicant_role varchar(16) NOT NULL DEFAULT 'renter', document_type varchar(32) NOT NULL, document_key varchar(512) NOT NULL, original_file_name varchar(255) NOT NULL, mime_type varchar(100) NOT NULL, status varchar(16) NOT NULL DEFAULT 'Pending', rejection_reason text, submitted_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.payments (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL, payer_id integer NOT NULL, method varchar(32) NOT NULL, status varchar(16) NOT NULL DEFAULT 'Pending', amount integer NOT NULL, currency varchar(3) NOT NULL DEFAULT 'MAD', provider_reference varchar(120) NOT NULL, simulated boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.commercial_lease_contracts (
  contract_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL UNIQUE, landlord_id integer NOT NULL, tenant_id integer NOT NULL, reference varchar(80) NOT NULL UNIQUE, lease_type varchar(32) NOT NULL, landlord_name varchar(255) NOT NULL, landlord_rc varchar(120), tenant_name varchar(255) NOT NULL, premises text NOT NULL, city varchar(100) NOT NULL, start_date timestamptz NOT NULL, end_date timestamptz NOT NULL, monthly_rent integer NOT NULL, deposit integer NOT NULL DEFAULT 0, pdf_key varchar(512), status varchar(16) NOT NULL DEFAULT 'Generated', legal_notice text NOT NULL, lease_end_reminder_task_uid varchar(65), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL, type varchar(40) NOT NULL, title varchar(255) NOT NULL, message text NOT NULL, href varchar(512), entity_type varchar(64), entity_id integer, read_at timestamptz, email_status varchar(16) NOT NULL DEFAULT 'not_sent', email_sent_at timestamptz, dedupe_key varchar(191), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, dedupe_key)
);
CREATE INDEX IF NOT EXISTS notifications_user_created_idx ON public.notifications(user_id, created_at);
CREATE INDEX IF NOT EXISTS notifications_user_unread_idx ON public.notifications(user_id, read_at);
CREATE TABLE IF NOT EXISTS public.booking_messages (
  message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL, sender_id integer NOT NULL, recipient_id integer NOT NULL, body text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS booking_messages_booking_created_idx ON public.booking_messages(booking_id, created_at);
CREATE INDEX IF NOT EXISTS booking_messages_recipient_unread_idx ON public.booking_messages(recipient_id, read_at);
CREATE TABLE IF NOT EXISTS public.audit_logs (
  audit_log_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id integer NOT NULL, action varchar(120) NOT NULL, entity_type varchar(80) NOT NULL, entity_id integer, before_data text, after_data text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON public.audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS audit_logs_actor_created_idx ON public.audit_logs(actor_id, created_at);
CREATE TABLE IF NOT EXISTS public.refund_requests (
  refund_request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL, requested_by integer NOT NULL, amount integer NOT NULL, reason text NOT NULL, status varchar(16) NOT NULL DEFAULT 'Pending', admin_note text, reviewed_by integer, created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.platform_settings (
  setting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, commission_rate_basis_points integer NOT NULL DEFAULT 1000, vat_rate_basis_points integer NOT NULL DEFAULT 2000, updated_by integer, updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.payout_requests (
  payout_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id integer NOT NULL, amount integer NOT NULL, method varchar(32) NOT NULL, status varchar(16) NOT NULL DEFAULT 'Pending', reference varchar(120), admin_note text, reviewed_by integer, created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.booking_vouchers (
  voucher_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL UNIQUE, renter_id integer NOT NULL, code varchar(80) NOT NULL UNIQUE, qr_payload text NOT NULL, status varchar(16) NOT NULL DEFAULT 'Issued', issued_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.invoices (
  invoice_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, invoice_number varchar(80) NOT NULL UNIQUE, booking_id integer NOT NULL, payment_id integer NOT NULL, payer_id integer NOT NULL, subtotal integer NOT NULL, commission_fee integer NOT NULL, vat_rate_basis_points integer NOT NULL DEFAULT 2000, vat_amount integer NOT NULL, total integer NOT NULL, currency varchar(3) NOT NULL DEFAULT 'MAD', status varchar(16) NOT NULL DEFAULT 'Issued', cancellation_policy_version varchar(80), cancellation_policy_snapshot text, cancellation_policy_fingerprint varchar(80), cancellation_policy_accepted_at timestamptz, cancellation_policy_accepted_by integer, issued_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.disputes (
  dispute_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id integer NOT NULL, opened_by integer NOT NULL, type varchar(120) NOT NULL, description text NOT NULL, status varchar(16) NOT NULL DEFAULT 'Open', resolution_note text, reviewed_by integer, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.dispute_attachments (
  attachment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dispute_id integer NOT NULL, file_key varchar(512) NOT NULL, original_file_name varchar(255) NOT NULL, mime_type varchar(100) NOT NULL, file_size integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.support_tickets (
  ticket_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL, subject varchar(255) NOT NULL, category varchar(120) NOT NULL, description text NOT NULL, status varchar(16) NOT NULL DEFAULT 'Open', last_response text, responded_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
