-- B2-Rent PostgreSQL baseline for Supabase.
-- This migration is deliberately isolated from public/auth/storage schemas.
-- It creates no sample data and never alters existing Supabase tables.

begin;

create schema if not exists b2rent;

create table if not exists b2rent.schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

create table if not exists b2rent.users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  whatsapp_phone varchar(32),
  commercial_register varchar(120),
  agency_name varchar(180),
  agency_logo_url text,
  agency_phone varchar(32),
  agency_email varchar(320),
  agency_address varchar(255),
  agency_website varchar(255),
  agency_latitude varchar(32),
  agency_longitude varchar(32),
  agency_hours text,
  login_method varchar(64),
  password_hash varchar(255),
  role text not null default 'user' check (role in ('renter', 'owner', 'admin', 'user')),
  legal_consent_version varchar(80),
  legal_consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists b2rent.listings (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references b2rent.users(id) on delete restrict,
  title text not null,
  description text,
  category varchar(64) not null check (category in ('car', 'real_estate')),
  price_per_day integer not null check (price_per_day >= 0),
  image_url text,
  status text not null default 'Published' check (status in ('Pending', 'Approved', 'Available', 'Rented', 'Rejected', 'Published')),
  city varchar(64) not null default 'الدار البيضاء',
  fuel_type varchar(32),
  transmission varchar(32),
  rooms integer not null default 0 check (rooms >= 0),
  office_type varchar(64),
  rental_period text check (rental_period in ('daily', 'monthly', 'yearly')),
  amenities text,
  availability jsonb,
  ical_import_url text,
  ical_export_token varchar(96) unique,
  ical_imported_ranges jsonb,
  ical_last_synced_at timestamptz,
  ical_sync_status text not null default 'never' check (ical_sync_status in ('never', 'ok', 'error')),
  ical_sync_error varchar(500),
  created_at timestamptz not null default now()
);

create table if not exists b2rent.listing_analytics_events (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references b2rent.listings(id) on delete cascade,
  event_type text not null check (event_type in ('view', 'whatsapp_click', 'contact_click')),
  visitor_key varchar(128),
  created_at timestamptz not null default now()
);

create table if not exists b2rent.bookings (
  id bigint generated by default as identity primary key,
  renter_id bigint not null references b2rent.users(id) on delete restrict,
  listing_id bigint not null references b2rent.listings(id) on delete restrict,
  secondary_listing_id bigint references b2rent.listings(id) on delete restrict,
  start_date timestamptz not null,
  end_date timestamptz not null,
  total_price integer not null check (total_price >= 0),
  commission_fee integer not null check (commission_fee >= 0),
  net_profit integer not null check (net_profit >= 0),
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed', 'Cancelled')),
  cancellation_policy_version varchar(80),
  cancellation_policy_snapshot text,
  cancellation_policy_fingerprint varchar(80),
  cancellation_policy_accepted_at timestamptz,
  cancellation_policy_accepted_by bigint references b2rent.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (end_date > start_date)
);

create table if not exists b2rent.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references b2rent.bookings(id) on delete restrict,
  listing_id bigint not null references b2rent.listings(id) on delete restrict,
  user_id bigint not null references b2rent.users(id) on delete restrict,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists b2rent.kyc_submissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references b2rent.users(id) on delete restrict,
  applicant_role text not null default 'renter' check (applicant_role in ('renter', 'owner', 'company')),
  document_type text not null check (document_type in ('cni', 'commercial_register')),
  document_key varchar(512) not null,
  original_file_name varchar(255) not null,
  mime_type varchar(100) not null,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  rejection_reason text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists b2rent.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references b2rent.bookings(id) on delete restrict,
  payer_id bigint not null references b2rent.users(id) on delete restrict,
  method text not null check (method in ('cmi_card', 'bank_transfer')),
  status text not null default 'Pending' check (status in ('Pending', 'Succeeded', 'Failed')),
  amount integer not null check (amount >= 0),
  currency varchar(3) not null default 'MAD',
  provider_reference varchar(120) not null,
  simulated boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists b2rent.commercial_lease_contracts (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references b2rent.bookings(id) on delete restrict,
  landlord_id bigint not null references b2rent.users(id) on delete restrict,
  tenant_id bigint not null references b2rent.users(id) on delete restrict,
  reference varchar(80) not null unique,
  lease_type text not null check (lease_type in ('commercial', 'professional')),
  landlord_name varchar(255) not null,
  landlord_rc varchar(120),
  tenant_name varchar(255) not null,
  premises text not null,
  city varchar(100) not null,
  start_date timestamptz not null,
  end_date timestamptz not null,
  monthly_rent integer not null check (monthly_rent >= 0),
  deposit integer not null default 0 check (deposit >= 0),
  pdf_key varchar(512),
  status text not null default 'Generated' check (status in ('Draft', 'Generated', 'Signed')),
  legal_notice text not null,
  lease_end_reminder_task_uid varchar(65),
  created_at timestamptz not null default now(),
  check (end_date > start_date)
);

create table if not exists b2rent.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references b2rent.users(id) on delete cascade,
  type text not null check (type in ('booking_new', 'booking_accepted', 'booking_rejected', 'listing_approved', 'listing_rejected', 'lease_expiring', 'voucher_issued', 'system')),
  title varchar(255) not null,
  message text not null,
  href varchar(512),
  entity_type varchar(64),
  entity_id bigint,
  read_at timestamptz,
  email_status text not null default 'not_sent' check (email_status in ('not_sent', 'sent', 'skipped', 'failed')),
  email_sent_at timestamptz,
  dedupe_key varchar(191),
  created_at timestamptz not null default now(),
  unique (user_id, dedupe_key)
);

create table if not exists b2rent.booking_messages (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references b2rent.bookings(id) on delete cascade,
  sender_id bigint not null references b2rent.users(id) on delete restrict,
  recipient_id bigint not null references b2rent.users(id) on delete restrict,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists b2rent.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint not null references b2rent.users(id) on delete restrict,
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id bigint,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists b2rent.refund_requests (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references b2rent.bookings(id) on delete restrict,
  requested_by bigint not null references b2rent.users(id) on delete restrict,
  amount integer not null check (amount >= 0),
  reason text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected', 'Paid')),
  admin_note text,
  reviewed_by bigint references b2rent.users(id) on delete set null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists b2rent.platform_settings (
  id bigint generated by default as identity primary key,
  commission_rate_basis_points integer not null default 1000 check (commission_rate_basis_points between 0 and 10000),
  vat_rate_basis_points integer not null default 2000 check (vat_rate_basis_points between 0 and 10000),
  updated_by bigint references b2rent.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists b2rent.payout_requests (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references b2rent.users(id) on delete restrict,
  amount integer not null check (amount >= 0),
  method text not null check (method in ('bank_transfer', 'cash_plus', 'wafacash')),
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Paid', 'Rejected')),
  reference varchar(120),
  admin_note text,
  reviewed_by bigint references b2rent.users(id) on delete set null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists b2rent.booking_vouchers (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references b2rent.bookings(id) on delete restrict,
  renter_id bigint not null references b2rent.users(id) on delete restrict,
  code varchar(80) not null unique,
  qr_payload text not null,
  status text not null default 'Issued' check (status in ('Issued', 'Revoked')),
  issued_at timestamptz not null default now()
);

create table if not exists b2rent.invoices (
  id bigint generated by default as identity primary key,
  invoice_number varchar(80) not null unique,
  booking_id bigint not null references b2rent.bookings(id) on delete restrict,
  payment_id bigint not null references b2rent.payments(id) on delete restrict,
  payer_id bigint not null references b2rent.users(id) on delete restrict,
  subtotal integer not null check (subtotal >= 0),
  commission_fee integer not null check (commission_fee >= 0),
  vat_rate_basis_points integer not null default 2000 check (vat_rate_basis_points between 0 and 10000),
  vat_amount integer not null check (vat_amount >= 0),
  total integer not null check (total >= 0),
  currency varchar(3) not null default 'MAD',
  status text not null default 'Issued' check (status in ('Pending', 'Issued')),
  cancellation_policy_version varchar(80),
  cancellation_policy_snapshot text,
  cancellation_policy_fingerprint varchar(80),
  cancellation_policy_accepted_at timestamptz,
  cancellation_policy_accepted_by bigint references b2rent.users(id) on delete set null,
  issued_at timestamptz not null default now()
);

create table if not exists b2rent.disputes (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references b2rent.bookings(id) on delete restrict,
  opened_by bigint not null references b2rent.users(id) on delete restrict,
  type varchar(120) not null,
  description text not null,
  status text not null default 'Open' check (status in ('Open', 'UnderReview', 'Resolved', 'Rejected')),
  resolution_note text,
  reviewed_by bigint references b2rent.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists b2rent.dispute_attachments (
  id bigint generated by default as identity primary key,
  dispute_id bigint not null references b2rent.disputes(id) on delete cascade,
  file_key varchar(512) not null,
  original_file_name varchar(255) not null,
  mime_type varchar(100) not null,
  file_size integer not null check (file_size >= 0),
  created_at timestamptz not null default now()
);

create table if not exists b2rent.support_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references b2rent.users(id) on delete restrict,
  subject varchar(255) not null,
  category varchar(120) not null,
  description text not null,
  status text not null default 'Open' check (status in ('Open', 'InProgress', 'Resolved')),
  last_response text,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists listings_owner_idx on b2rent.listings(owner_id);
create index if not exists listings_public_idx on b2rent.listings(status, category, city);
create index if not exists listing_analytics_event_idx on b2rent.listing_analytics_events(listing_id, event_type);
create index if not exists listing_analytics_created_idx on b2rent.listing_analytics_events(listing_id, created_at);
create index if not exists bookings_listing_dates_idx on b2rent.bookings(listing_id, start_date, end_date);
create index if not exists notifications_user_created_idx on b2rent.notifications(user_id, created_at);
create index if not exists notifications_unread_idx on b2rent.notifications(user_id, read_at);
create index if not exists booking_messages_booking_idx on b2rent.booking_messages(booking_id, created_at);
create index if not exists booking_messages_recipient_idx on b2rent.booking_messages(recipient_id, read_at);
create index if not exists audit_logs_entity_idx on b2rent.audit_logs(entity_type, entity_id);
create index if not exists refund_requests_booking_idx on b2rent.refund_requests(booking_id, created_at);
create index if not exists refund_requests_requester_idx on b2rent.refund_requests(requested_by, status);

insert into b2rent.schema_migrations(version)
values ('0001_b2rent_schema')
on conflict (version) do nothing;

commit;
