import type { Express } from "express";
import { createRequire } from "node:module";

type ServerBundle = {
  createApp: () => Express;
};

// Vercel compiles this entry point separately. Load the server code from the
// CJS bundle generated by `build:vercel-api` so internal TypeScript imports
// and path aliases do not have to be resolved by the Serverless runtime.
const require = createRequire(import.meta.url);
const { createApp } = require("./_generated/app.cjs") as ServerBundle;

// Vercel invokes this Express app as a Node Serverless Function. Static React
// assets are published from dist/public by the Vercel build configuration.
const app = createApp();

export default app;
